services:
  frontend:
    image: frontend
    # build:
    #   context: ./client
      # dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    image: backend
    # build:
    #   context: ./server
      # dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai_balance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./server/full_dump.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   postgres_data:
