"""Add mood_category to Entry

Revision ID: 0aa16d642ba4
Revises: d5f94c8a4c8c
Create Date: 2025-06-02 14:35:25.074374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa16d642ba4'
down_revision: Union[str, None] = 'd5f94c8a4c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('mood_category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'mood_category')
    # ### end Alembic commands ###
