"""Fix created_at default now()

Revision ID: 3919fc2d8df1
Revises: 5c85c09c49d5
Create Date: 2025-05-30 14:00:55.483026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3919fc2d8df1'
down_revision: Union[str, None] = '5c85c09c49d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

op.alter_column(
    'entries',
    'created_at',
    server_default=sa.text('now()'),
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
