"""Add ON DELETE CASCADE to user_id FKs

Revision ID: 489c306f6ae0
Revises: 0aa16d642ba4
Create Date: 2025-06-03 15:24:52.831781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489c306f6ae0'
down_revision: Union[str, None] = '0aa16d642ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entries_user_id_fkey'), 'entries', type_='foreignkey')
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('goals_user_id_fkey'), 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key(op.f('goals_user_id_fkey'), 'goals', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_foreign_key(op.f('entries_user_id_fkey'), 'entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
