name: Deploy changes to Dev

on:
  push:
     branches:
       - main
  workflow_dispatch:

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get ssh key
      run: |
        echo "${{ secrets.SSH_KEY }}" > ../id_ed25519
        chmod 600 ../id_ed25519

    - name: Get repo name
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

    - name: Get ec2 instance IP
      run: |
        PUBLIC_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=${{ env.REPO_NAME }}" "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].PublicIpAddress" \
          --output text)

        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

    - name: Create .env for frontend
      run: |
        cat <<EOF > ./client/.env
        ${{ secrets.CLIENT_ENV }}
        EOF
        cat ./client/.env

    - name: Create .env for backend
      run: |
        cat <<EOF > ./server/.env
        ${{ secrets.SERVER_ENV }}
        EOF
        cat ./server/.env

    - name: Deploy to dev server
      run: |
        cd ./server
        docker build --platform linux/amd64 -f ./Dockerfile -t backend .
        cd ../client
        docker build --platform linux/amd64 -f ./Dockerfile -t frontend .
        cd ..
        ssh -o StrictHostKeyChecking=no -i ../id_ed25519 ubuntu@${{ env.PUBLIC_IP }} 'docker system prune -af'

        docker save backend:latest  | ssh -o StrictHostKeyChecking=no -i ../id_ed25519 ubuntu@${{ env.PUBLIC_IP }} 'docker load'
        docker save frontend:latest  | ssh -o StrictHostKeyChecking=no -i ../id_ed25519 ubuntu@${{ env.PUBLIC_IP }} 'docker load'                 
                 
        ssh -o StrictHostKeyChecking=no -i ../id_ed25519 ubuntu@${{ env.PUBLIC_IP }} << 'EOF'
        cd ~/${{ env.REPO_NAME }}
        # git fetch origin 
        # git reset --hard origin/main
        git pull
        docker compose down
        docker compose up --build -d
        EOF
